'''
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
'''

import time

start = time.time()

from functools import reduce

# Only n = 32 and larger produces triangle numbers larger than 500
n = 32

while True:
    prime_factors = {}
    triangle_number = n * (n + 1) / 2
    i = 2
    while i <= triangle_number:
        if triangle_number % i == 0:
            triangle_number /= i
            if i in prime_factors:
                prime_factors[i] += 1
            else:
                prime_factors[i] = 1
            i -= 1
        i += 1
    powers = map(lambda x: (x + 1), prime_factors.values())
    divisors = reduce(lambda x, y: x * y, powers)
    if divisors > 500:
        print(int(((n - 1) * (n)) / 2))
        break
    n += 1

end = time.time()

# Executes in 8.30 seconds
print(end - start)
