'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

import time

start = time.time()

a = 1

b = 2

solution = [2]

while a + b < 4000000:
    a = a + b
    if a % 2 == 0:
        solution.append(a)
    b = a + b
    if b > 4000000:
        break
    if b % 2 == 0:
        solution.append(b)

print(sum(solution))

end = time.time()

# Executes in 0.0 seconds
print(end - start)
