'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import time

start = time.time()

flag = True

i = 286

def pentagonal(n): # Test for pentagonal numbers from Wikipedia
	if (((24 * n + 1) ** 0.5) + 1) % 6 == 0:
		return True
	return False

def hexagonal(n): # Test for hexagonal numbers from Wikipedia
	if (((8 * n + 1) ** 0.5) + 1) % 4 == 0:
		return True
	return False

while flag:
	triangleNumber = int((i * (i + 1)) / 2)
	if pentagonal(triangleNumber) and hexagonal(triangleNumber):
		print(triangleNumber)
		flag = False
	else:
		i += 1
		print(i)

end = time.time()

print(end - start) # Executed in 0.578 seconds
